dist: xenial

language: python
python:
    - "3.7"

install:
     - make dep
     - make dev

script:
    # run static analysis and format check
    - make test

cache:
  directories:
    ~/rl-examples
