language: python

python:
    - "3.6"

env:
    - pip install -r requirements.txt

sudo: false

install:
    # flake8: static analysis and style checks
    - pip install -U flake8
    - pip install -U flake8-bugbear
    - pip install -U flake8-docstrings

script:
    # run static analysis and styls check
    - flake8 .
