language: python

python:
    - "3.6"

# env:
#     - pip install -r requirements.txt

sudo: false

install:
    - make dev
    - make dep

script:
    # run static analysis and styls check
    - make test
